version: '3.3'
services:
    wrestling-api:
        build:
          context: .
        ports:
          - 8002:8000
    db:
      image: amazon/dynamodb-local
      restart: unless-stopped
      ports:
        - 8000:8000